### ISSUE TITLE
Build can't find spa-cat.t1x

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-spa-cat#1]
Build fails with:
`make[1]: *** No rule to make target 'spa-cat.t1x', needed by 'all-am'.  Stop.`

**Comment by xavivars** [comment]
I'm taking care of it

**Comment by xavivars** [comment]
@TinoDidriksen , I've done a cleanup of the `Makefile.am`, and a make dist is now working.

If/when you confirm it, feel free to close this ticket.
