### ISSUE TITLE
Apostofació d'impost en català

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#15]
Quan traduim del castellà al català, la traducció generada en català és incorrecta perquè no s'apostofa 

Exemples:
* El impuesto es caro > El impost és car (hauria de ser L'impost)

**Comment by jaumeortola** [comment]
No ho puc reproduir:
```
$ myapertium.sh "El impuesto es caro." spa-cat
L'impost és car.
```

**Comment by jordimas** [comment]
Bé, jo tampoc el puc reproduir ja. Ho tanco.

**Comment by jordimas** [comment]
He comprovat també que la resta de tiquets es puguin reproduir, i sí, la resta es poden reproduir en local.
