### ISSUE TITLE
Repetició de la preposició amb realengo

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#17]
En la traducció spa > cat

Para ello nos hemos basado en la documentación disponible para destacadas ciudades de realengo: Burgos, Madrid, Murcia, Sevilla > Per a això ens hem basat en la documentació disponible per a destacades ciutats *de del* patrimoni reial: Burgos, Madrid, Múrcia, Sevilla

Sembla relacionat amb:

apertium-spa-cat.spa-cat.metadix:<e r="LR"><p><l>realengo<s n="adj"/></l>            <r>del<b/>patrimoni<b/>reial<s n="adj"/><s n="mf"/><s n="sp"/></r></p></e>

**Comment by jaumeortola** [comment]
Amb això hauria d'estar arreglat: https://github.com/apertium/apertium-spa-cat/commit/075b23f171bfc3556dfaf0aab3265f7790243324
Aquí hi ha la complicació que realengo és nom i adjectiu, i reialenc només nom.

**Comment by jaumeortola** [comment]
En els tests és veu que la solució és bona.
