### ISSUE TITLE
Important: perquè - para que (català -> castellà)

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#21]
Examples on en la traducció del català a castellà usem _perquè_ en comptes de _para que_:

* Us envio adjunt el meu currículum, fotocòpies dels títols que tinc i dues cartes de referències perquè tingueu informació complementària sobre la meva persona.  -> Os envío adjunto mi currículum, fotocopias de los títulos que tengo y dos cartas de referencias **porque** tengáis información complementaria sobre mi persona.
* Un document que serveix per transmetre informació tècnica i fer una proposta o aportar unes conclusions o presentar la solució a un problema perquè les persones interessades puguin adoptar una decisió adequada a la llei i a les circumstàncies. > Un documento que sirve para transmitir información técnica y hacer una propuesta o aportar unas conclusiones o presentar la solución a un problema **porque** las personas interesadas puedan adoptar una decisión adecuada a la ley y a las circunstancias.
* us preguem que ens ho feu saber perquè us puguem donar la resposta més adequada a les vostres necessitats. -> Os rogamos que nos lo hacéis saber Os rogamos que nos lo hacéis saber **porque** os podamos dar la respuesta más adecuada a vuestras necesidades. os podamos dar la respuesta más adecuada a vuestras necesidades.
* Et deixo el llibre perquè el llegeixis -> Te dejo el libro **porque** lo leas. 
* Regueu les plantes perquè no es morin -> Regáis las plantas **porque** no se mueran. 

Aquest error és comú en textos administratius (i segurament en altres àmbits).

El perquè en català té diverses finalitats. Quan s'usa per expressar l'objectiu, en castellà  cal traduir-ho per "para que"

**Comment by jaumeortola** [comment]
No hauria de ser especialment complicat. Quan és un verb en subjuntiu és "para que", i en indicatiu és "porque". Pot haver-hi casos de coincidència subjuntiu/indicatiu (més amb les formes verbals valencianes).  
Les regles són aquí: https://github.com/apertium/apertium-spa-cat/blob/e9f87b3bd3737954dd0e58aedbffde9c2656d776/apertium-spa-cat.cat-spa.metalrx#L896
S'haurien d'intentar generalitzar amb `<repeat from="" upto="">` en comptes de patrons fixos de frases.

**Comment by jaumeortola** [comment]
Hi havia problema molt més bàsic: la traducció `perquè->para que` estava inactiva!

**Comment by jaumeortola** [comment]
https://github.com/apertium/apertium-spa-cat/commit/85d4c04211ba60e6f57212db914d1a0cadcc9eb2

**Comment by xavivars** [comment]
Totes les regles del LRX que has comentat no feien falta?

**Comment by jaumeortola** [comment]
> Totes les regles del LRX que has comentat no feien falta?

Queden incloses en la que he fet amb `<repeat>`. De totes maneres, tot això era inoperatiu perquè la traducció `perquè->para que` estava desactivada.

**Comment by jaumeortola** [comment]
La idea de la regla és senzilla (una altra cosa és que estigui ben implementada). Si hi ha un verb en subjuntiu és "para que". Si és indicatiu és "porque". Hi ha algunes ambigüitats, sobretot en valencià: perquè pense -> porque pienso // para que piense
