### ISSUE TITLE
Incloent-hi

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#22]
Castellà:

Determinar de qué manera dichos factores están siendo desarrollados en las actuales intervenciones, incluyendo las posibles mejoras que se puedan llevar a cabo.

Català:

Determinar de quina manera aquests factors estan sent desenvolupats en les actuals intervencions, **incloent** les possibles millores que es puguin dur a terme.

Incloent caldria que fos incloent-hi

**Comment by jaumeortola** [comment]
https://github.com/apertium/apertium-spa-cat/commit/6300b7d5b4caa048a898d346d58c8d6441ea6dd4

**Comment by jaumeortola** [comment]
https://github.com/apertium/apertium-spa-cat/commit/b62e87ff4e0ee8c34fe77bb7500d126a9f01d4b2
