### ISSUE TITLE
Traducció diferent de la mateixa frase (cat -> spa)

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#38]
Si traduim aquest text spa-cat:

portes abatibles cap a l’exterior o correderes, i que compleixen les condicions de l’itinerari accessible
portes abatibles cap a l’exterior o correderes, i que compleixen les condicions de l’itinerari accessible

Obtenim:

puertas abatibles hacia el exterior o correderes, y que cumplen las condiciones del itinerario accesible
**llevas** abatibles hacia el exterior o correderes, y que cumplen las condiciones del itinerario accesible

No sembla lògic que la traducció de la mateixa frase canviï així. Si afegeixes un punt al final de la primera frase.

**Comment by xavivars** [comment]
El salt de línia no es considera un final de frase, i el desambiguador considera que després d'un nom+adj és més probable un verb que un nom.

Per tant, el traductor no ho veu com "la mateixa frase", sinó una continuació de la primera

**Comment by jordimas** [comment]
Gràcies Xavi, imaginava que anava per aquí la cosa. En aquest cas, l'error venia d'un corpus, on el problema era molt evident perquè la mateixa frase estava duplicada i es traduïa diferent.  

Entenc que la única opció aquí es considerar el salt de línia com a nova frase, però això segurament obrirà un ventall de problemes en la direcció contraria (assumir que és nova frase quan no ho és).

**Comment by xavivars** [comment]
Si, crec que causaria problemes a altres llocs. A més, crec que no és una cosa que es puga controlar a nivell de parell d'idioma, sinó que està a nivell d'apertium
