### ISSUE TITLE
Issue with this package

### ISSUE THREAD

**Issue by chechu-arias** [apertium/apertium-spa-cat#4]
I've been using apertium-python with this package to translate from spanish to catalan and the other way around.

I followed the trace in Github and my installed library and got to [here](https://github.com/apertium/apertium-python/blob/bf803486bb0007751e12d5a54efd0caf03e6aff1/apertium/utils.py#L179) where I just locally printed my file location and changed: 
`lt-proc -x '/usr/share/apertium/apertium-spa-cat/spa-cat.autopgen-diacritics-vells.bin'`
to
`lt-proc '/usr/share/apertium/apertium-spa-cat/spa-cat.autopgen-diacritics-vells.bin'`
because lt-proc doesn't have a -x option.

I got rid of this `lt-proc: invalid option -- 'x'` error that I kept getting.

Still, my output has `^que/*que$ ^es/*es$` this format, with the syntax `^word/*word$` and I don't know how to change it or configure the Python object.

I've read the [man page of lt-proc](https://man.cx/lt-proc(1)) where it says:

> ’[’, ’]’, ’$’, ’^’, ’/’, ’+’ ) are special chars used for format and encapsulation. They should be escaped if they have to be used literally, for instance: ’
[ ’...’
] ’ are ignored and the format of a linefeed is ’
^...$ ’.

But I'm not getting it right I think, just wanted to ask for some help and let you know about the -x error.

**Comment by xavivars** [comment]
You may have an old version of lttoolbox. `lt-proc -x` was added more than 2 years ago: https://github.com/apertium/lttoolbox/pull/29

**Comment by chechu-arias** [comment]
I've printed the list of lttoolbox packages that I have and I got this:

liblttoolbox3-3.5-1/unknown,now 3.5.3+g493~15a208dd-1~focal1 amd64 [installed,automatic]
lttoolbox-dev/unknown,now 3.5.3+g493~15a208dd-1~focal1 amd64 [installed,automatic]
lttoolbox/unknown,now 3.5.3+g493~15a208dd-1~focal1 amd64 [installed,automatic]
python3-lttoolbox/unknown,now 3.5.3+g493~15a208dd-1~focal1 amd64 [installed]

Tried to manually upgrade them, but they were all the newest version.

I also tried reinstalling all the apertium packages with same result.

**Comment by xavivars** [comment]
I think I found the problem. `lttoolbox` python's wrapper doesn't support `-x`... 🤦 

https://github.com/apertium/lttoolbox/blob/master/python/lttoolbox.i.in

**Comment by chechu-arias** [comment]
Okay, so then that's resolved 🤣.

Apart from that, do you know if the format of the output is always the same ( `^word/*word$` ) ?

**Comment by xavivars** [comment]
That's the format for unknown words

**Comment by xavivars** [comment]
I'm closing this issue, moving it https://github.com/apertium/lttoolbox/issues/106
