### ISSUE TITLE
Important: spa-> cat confusió hoja - full/fulla

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#48]
SPA -> CAT

ADJUNTAR EN HOJA APARTE DOCUMENTO QUE ACREDITE QUE HA PRESENTADO LA QUEJA O RECLAMACIÓN ANTE EL SERVICIO O DEPARTAMENTO DE ATENCIÓN AL CLIENTE O, EN SU CASO, EL DEFENSOR DEL CLIENTE O PARTÍCIPE, Y QUE HAN TRANSCURRIDO DOS MESES DESDE LA PRESENTACIÓN DE LA MISMA

ADJUNTAR EN **FULLA** APART DOCUMENT QUE ACREDITI QUE HA PRESENTAT LA QUEIXA O RECLAMACIÓ DAVANT EL SERVEI O DEPARTAMENT D'ATENCIÓ Al CLIENT O, EN EL SEU CAS, EL DEFENSOR DEL CLIENT O PARTÍCIP, I QUE HAN TRANSCORREGUT DOS MESOS DES DE LA PRESENTACIÓ DE LA MATEIXA

Ahora que ya sabes qué puedes mejorar de tu diario de vida, reescríbelo en una hoja aparte, cuidando de hacerlo con letra clara.
Ara que ja saps què pots millorar del teu diari de vida, reescriu-lo en una **fulla** a part, cuidant de fer-ho amb lletra clara.

CUANDO DIRIJA LA RECLAMACIÓN CONTRA LA ENTIDAD GESTORA DE SU PLAN DE PENSIONES ADJUNTE EN HOJA APARTE EL BOLETÍN DE ADHESIÓN AL PLAN DE PENSIONES Y DEMÁS DOCUMENTACIÓN CONTRACTUAL RECIBIDA.

QUAN DIRIGEIXI LA RECLAMACIÓ CONTRA L'ENTITAT GESTORA DEL SEU PLA DE PENSIONS ADJUNTI EN **FULLA** A part EL BUTLLETÍ D'ADHESIÓ Al PLA DE PENSIONS I ALTRA DOCUMENTACIÓ CONTRACTUAL REBUDA.

El problema és que hoja és polisèmica en castellà i segons el significat és full o fulla.

Aquest problema és molt comú en textos administratius ja que es parla sovint de full.

**Comment by jaumeortola** [comment]
He arreglat el cas concret de "full a part". Ja tenim molts casos de full/fulla controlats. Però segur que encara en queden molts pendents. 
https://github.com/apertium/apertium-spa-cat/commit/f55462b1d2fee14da5c9cb1cd6d296df57b893fe
