### ISSUE TITLE
spa ->  cat setencia - fallada

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#50]
Andrés Manuel López Obrador ha celebrado este martes el fallo de la Suprema Corte de Justicia de la Nación (SCJN), que ayer tumbó el caso del fiscal general de la República contra su familia política, y al mismo tiempo ha reiterado su confianza en el procurador.

Andrés Manuel López Obrador ha celebrat aquest dimarts la **fallada** de la Suprema Cort de Justícia de la Nació (SCJN), que ahir va tombar el cas del fiscal general de la República contra la seva família política, i al mateix temps ha reiterat la seva confiança en el procurador.

Así lo ha manifestado en nota de prensa STEI Intersindical, quien ha señalado que la sentencia responde a una demanda interpuesta por una docente de un colegio público de Mallorca. Ahora, la Administración tiene 15 días para recurrir el fallo.

Així ho ha manifestat en nota de premsa STEI Intersindical, qui ha assenyalat que la sentència respon a una demanda interposada per una docent d'un col·legi públic de Mallorca. Ara, l'Administració té 15 dies per a recórrer la **fallada**.

fallada -> sentencia

**Comment by jaumeortola** [comment]
Les traduccions que funcionen millor són "decisió" (en les frases anteriors) i, en un sentit molt concret i tècnic, "part dispositiva". "El fallo de la sentencia" -> "La part dispositiva de la sentència". 
Caldria completar una mica les regles amb més paraules del context de tribunals i jutges. 
https://github.com/apertium/apertium-spa-cat/commit/cb0c1aed3504e052d206e5b41dc9012cdc6f4639

**Comment by jordimas** [comment]
Sí, jo em basaria en exemples reals que surtin en el futur. Això és un gran pas i el podem ampliar amb futurs exemples.
