### ISSUE TITLE
spa -> cat afegir lèxic

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#52]
Lèxic que suggeriexo considerar incloure:

Castellà | Català | Comentari
-- | -- | --
Boletín Oficial del Estado | Butlletí Oficial de l'Estat |  
helicubierta | helicoberta |  
litigiosidad | ligitiositat |  
miniportátil | miniportàtil |  
Unidas Podemos | Unides Podem | Nom propi: partit polític
Podemos | Podem | Nom propi: partit polític
judicialización | judicialització |  
nucleación | nucleació |  
epistémica | epistèmic |

**Comment by jaumeortola** [comment]
Podemos/Podem potser requereix alguna regla especial, però probablement no.

No tinc clar que Boletín Oficial del Estado es tradueixi segons alguns llibres d'estil. La Generalitat Valenciana sembla que ho volia sense traduir. Però en la pàgina www.boe.es sí que tradueixen el nom. Per tant, és lògic traduir-ho.

**Comment by jaumeortola** [comment]
Ja està fet. Per poques paraules no val la pena aquesta feina. https://github.com/apertium/apertium-spa-cat/commit/1e208f16eb2833422d0fa2a22aa120e7eb548cfb
Normalment, vaig acumulant paraules en un full de càlcul, i quan n'hi ha unes quantes creo les entrades noves.
