### ISSUE TITLE
Makefile error in recursive-spa-cat branch

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-spa-cat#53]
```
python genvrdix.py cat .deps/spa-cat.dix >.deps/spa-cat.cat.dix
/bin/bash: line 1: python: command not found
make: *** [Makefile:865: .deps/spa-cat.cat.dix] Error 127
```

For recent distros of linux, you need to specify which version of python.

**Comment by xavivars** [comment]
That script was moved years ago to a shared place. So I guess the branch needs to be rebased on master

**Comment by MarcRiera** [comment]
Yes, the `recursive-spa-cat` branch was created in early 2020 and hasn't been updated since two years ago. The RTX-related commits don't modify the bidix, so it's just a matter of rebasing the branch.

**Comment by MarcRiera** [comment]
I've rebased the branch with master and it builds fine locally. @jonorthwash Could you please try if it works for you?

**Comment by jonorthwash** [comment]
Oof, I've gotten into really bad git states trying to pull this.  Do you have any guidance on how I can get this branch?  (I suppose I can always wipe it and make a fresh clone..)

**Comment by MarcRiera** [comment]
Rebasing rewrites history, so your local copy and GitHub have diverged. I'm sure there's a way to get your local copy in sync (especially if you don't have any pending local changes), but my git knowledge doesn't go that far. @xavivars?

**Comment by xavivars** [comment]
@jonorthwash , not sure if you still have this error, and in case you do, not sure if you also had local changes. But assuming you don't care about anything local, you can fix this with

```
git fetch
git reset --hard origin/recursive-spa-cat
```
