### ISSUE TITLE
spa -> cat craquelar<>clivellar

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#58]
SPA: Ambos hombres afirmaron que las pinturas hechas con sus respectivos métodos no se craquelarían, ni se verían alteradas por los efectos de la luz y el calor.

CAT: Tots dos homes van afirmar que les pintures fetes amb els seus respectius mètodes no es **craquelarían**, ni es veurien alterades pels efectes de la llum i la calor.

Correcció: Tots dos homes van afirmar que les pintures fetes amb els seus respectius mètodes no es **clivellarien**, ni es veurien alterades pels efectes de la llum i la calor."

Falta l'entrada craquelar<>clivellar al diccionari

**Comment by jaumeortola** [comment]
L'afegeixo al diccionari.
