### ISSUE TITLE
spa -> cat mostrant-los - mostrant-lis

### ISSUE THREAD

**Issue by jordimas** [apertium/apertium-spa-cat#60]
SPA: Sin embargo, cuando los adultos les enseñan a cómo cuidar y proteger la naturaleza mostrándoles ejemplos de personas que cuidan el medio ambiente, ellos sienten que un mundo mejor es posible.

CAT: No obstant això, quan els adults els ensenyen a com cuidar i protegir la naturalesa **mostrant-los** exemples de persones que cuiden el medi ambient, ells senten que un món millor és possible.

Correcció: No obstant això, quan els adults els ensenyen a com cuidar i protegir la naturalesa **mostrant-lis** exemples de persones que cuiden el medi ambient, ells senten que un món millor és possible."

**Comment by jaumeortola** [comment]
Això és proposta dels estudiants? "Mostrant-los" és correcte. "Mostrant-lis" no!
![imatge](https://user-images.githubusercontent.com/4289501/177993862-3ebb7cbe-4aca-4c08-b98e-9cb8d59a98cb.png)
