### ISSUE TITLE
cuál > quin/quina

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-spa-cat#73]
Actualment, "cuál" es marca com a "GD" però sempre es tradueix com a masculí perquè és un pronom catafòric (apareix abans que el referent). Caldria afegir-ho al mòdul d'anàfores, que ja forma part del parell.

Exemples d'errors:

No sé cuál de estos olivos es el mío. > No sé quin d'aquestes oliveres és el meu.

**Comment by jaumeortola** [comment]
Veig que en aquests casos la traducció ja es resol bé. No m'he parat a mirar com es fa.
> ¿Cuál es el problema? -> Quin és el problema?
> ¿Cuál es la solución? -> Quina és la solució?

**Comment by MarcRiera** [comment]
Ho acabo de resoldre a 29763ecb09f74dae0403a8269c8de30fabc8ac2c. Finalment, ho he fet amb reglès de trànsfer (com els casos on ja funcionava), perquè el mòdul d'anàfores encara no admet les catàfores: https://github.com/apertium/apertium-anaphora/issues/28

@AnnaEvaPeig Mireu si els casos que teniu queden ben resolts. Si n'hi ha cap que abans funcionés i ara no, ho podeu deixar anotat aquí en un comentari i miraré si les regles es poden millorar. Gràcies!

**Comment by AnnaEvaPeig** [comment]
Continua fent malament les construccions per les quals vaig introduir les entrades com a adverbi: cuál de las dos nomenclaturas > quin de les dos nomenclatures

Quan afegim un numeral davant del substantiu no ho fa bé: cuál de estas dos casas > quin d'estes dos cases

**Comment by jaumeortola** [comment]
Sí, els que diu Anna fallen. L'única solució és posar-hi més regles, una per cada estructura. És laboriós, però amb unes quantes més cobriríem la major part dels casos.

**Comment by MarcRiera** [comment]
He afegit dues regles més per a casos amb numerals, ara ja funcionen aquests casos.

**Comment by AnnaEvaPeig** [comment]
Sí, ho acabe de comprovar.

Moltes vegades, en catellà, fan l'error de no posar l'accent a l'interrogatiu "cuál". En aquest cas ens trobem casos com: cual de las dos nomenclaturas > com de les dos nomenclatures / cual de las partes será responsable > com de les parts serà responsable

Encara que siga incorrecte en castellà, es podria afegir "cual" sense accent a les regles anteriors per a solucionar aquests casos?

**Comment by MarcRiera** [comment]
Sí, i tant, afegiré "cual" com a forma secundària de "cuál" perquè el desambiguador faci la correcció en aquest context i la traducció sigui correcta.

**Comment by AnnaEvaPeig** [comment]
Perfecte. Ho acabe de comprovar i ja fa funcionen també aquests casos.
