### ISSUE TITLE
trucar (cat) -> llamar (spa)

### ISSUE THREAD

**Issue by jaumeortola** [apertium/apertium-spa-cat#77]
> La qüestió és que em van trucar divendres.

**Comment by jaumeortola** [comment]
Possible solució: 
* Traduir `trucar -> llamar` per defecte. 
* Afegir alguna excepció com ara "trucar la moto", etc.

**Comment by marcriera** [comment]
Acabo de pujar un canvi que soluciona parcialment el problema.

- `trucar` ara es pot traduir per `llamar` i és l'opció per defecte.
- En alguns casos, com `moto trucada` o `trucar el cotxe`, es tria `trucar` com a traducció.

**Comment by jaumeortola** [comment]
https://github.com/apertium/apertium-spa-cat/commit/649423bdec84d9394bff4391f00bc1b38f3f07fd (i següents)
