### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jcalve** [apertium/apertium-spa-cat#8]
Building fails with the following message:

```
apertium-metalrx apertium-spa-cat.spa-cat.metalrx .deps/apertium-spa-cat.spa-cat.lrx
lrx-comp .deps/apertium-spa-cat.spa-cat.lrx spa-cat.autolex.bin
Error (line 8067): <select> is not permitted inside <repeat>.
make: *** [spa-cat.autolex.bin] Error 1
```

I'm using apertium and its tools built from master.

**Comment by mr-martian** [comment]
That was a change in https://github.com/apertium/apertium-lex-tools/commit/c5811060957893ce122b4bcebcf40294ea850397 (January 20) - could you check whether your copy of that repo is up-to-date?

**Comment by jcalve** [comment]
That was the problem, thanks.
